### ISSUE TITLE
[documentation] "How to use" section could be in a step-by-step format

### ISSUE THREAD

**Issue by kassalanche** [na2hiro/remix-auth-twitter#2]
The "How to use" section could be in a step-by-step format in the following order:

1. Setup authenticator (+link). Currently, it's at the very bottom
2. Add X to package JSON.
3. Code snippet with TwitterStrategy (same as now) + **add import**.

**Comment by na2hiro** [comment]
Updated with descriptions! https://github.com/na2hiro/remix-auth-twitter/commit/a1cce81dae1af0de99134fe68c21bce2929224e3
