### ISSUE TITLE
Dependencies narrow down: exclude react-dom

### ISSUE THREAD

**Issue by arielshulman** [na2hiro/remix-auth-twitter#23]
Hey, 
I'm looking at the [dependencies](https://github.com/na2hiro/remix-auth-twitter/blob/06f0249df608b107f72c4c3d789f5d37544c83de/package.json#L68) of the package.
Do you think it will be able narrow it down a bit? not sure if `react-dom` is used at all in the package code.

Thanks 🙏

**Comment by na2hiro** [comment]
You're right, let me remove it. Thanks!

**Comment by na2hiro** [comment]
Published `0.1.2` https://github.com/na2hiro/remix-auth-twitter/releases/tag/v0.1.2
